#!/usr/bin/env bash

location="${RDM_UTILS_LOCATION:-/usr/share/rdm-utils}/commands"

while read -r var
do
  [[ -f $var ]] || continue
  source "$var"
done < <(find "$location" -type f)

unset location
