#!/usr/bin/env bash

# Create /nested/or/not/direcotry
mago()
{
    [[ $# -ne 1 ]] && usage "mago /path/to/new/directory/"
    mkdir -p "$1"
    #shellcheck disable=SC2164
    cd "$1"
}

# Creates directory with name starting with current date optionally concatenated with name given, doesn't nest
magot()
{
    [[ $# -ne 1 ]] && usage "mago directory"
    dir="$(date -Im)-$1"
    dir="${dir%-}"
    mago "$dir"
}

# helper, creates dir, then uses $prog -t "$dir" "$@" where prog is meant to be mv or cp
abstract_mago_moving()
{
    prog=$1
    ver=$2
    shift 2
    [[ $# -lt 2 ]] && usage "$ver DIR FILES..."
    dir=$1
    shift
    mkdir -p "$dir"
    $prog -t "$dir" "$@"
    #shellcheck disable=SC2164
    cd "$dir"
}

magom()
{
    abstract_mago_moving mv magot "$@"
}


magoc()
{
    abstract_mago_moving cp magoc "$@"
}
